---
name: Code checks

"on":
  push:

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mypy

      - name: Run mypy checks
        run: |
          python3 -m mypy --show-error-codes --show-column-numbers src
